[package]
name = "scheduling_project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.1"
rand_distr = "0.5.1"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
uuid = { version = "1.17.0", features = ["v7"] }
